- name: Deploy Backend
  hosts: backend
  become: true
  tasks:
    - name: Install Node.js and npm
      yum:
        name:
          - nodejs
          - npm
        state: present

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes

    - name: Upload backend archive to EC2
      copy:
        src: backend.tar.gz
        dest: /home/ec2-user/backend.tar.gz

    - name: Extract backend code on EC2
      shell: |
        rm -rf /home/ec2-user/backend
        mkdir -p /home/ec2-user/backend
        tar -xzf /home/ec2-user/backend.tar.gz -C /home/ec2-user/backend

    - name: Upload Firebase service key
      copy:
        src: firebase-service-key.json
        dest: /home/ec2-user/backend/firebase-service-key.json
        owner: ec2-user
        group: ec2-user
        mode: '0600'

    - name: Install backend dependencies
      shell: npm install
      args:
        chdir: /home/ec2-user/backend/

    - name: Start backend with PM2
      shell: |
        pm2 delete parcel-backend || true
        pm2 start server.js --name parcel-backend
        pm2 save
      args:
        chdir: /home/ec2-user/backend/

---

- name: Deploy Frontend (via nginx)
  hosts: frontend
  become: true
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Upload frontend build archive to EC2
      copy:
        src: frontend-build.tar.gz
        dest: /home/ec2-user/frontend-build.tar.gz

    - name: Extract frontend build on EC2
      shell: |
        mkdir -p /usr/share/nginx/html
        tar -xzf /home/ec2-user/frontend-build.tar.gz -C /usr/share/nginx/html

    - name: Remove default nginx config (if exists)
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Configure nginx for SPA
      copy:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
        backup: yes
        owner: root
        group: root
        mode: 0644

    - name: Test nginx config before reload
      shell: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0
      ignore_errors: false

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
